### ISSUE TITLE
Membership Monthly All 

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#2]
Select Filter: Membership/Monthly/All
The first page of result shows members with no expiration date or status. Click on detail, it showed this member is expired. Is there something wrong with the data? 

<img width="1034" alt="screen shot 2017-02-21 at 9 30 57 pm" src="https://cloud.githubusercontent.com/assets/7178461/23198551/360e360e-f87d-11e6-9734-90403bdac3c4.png">

**Comment by sagarjagdish** [comment]
@omnitekinc  : expiry date not exist in client given database for all those member and because of that we are not showing that date on listing but when we go for edit it's show member expired (red highlighted) because we not found expiry date.

Please let us know in this case which action required on listing and edit case. all are AERA existing members.

**Comment by omnitekinc** [comment]
In this case I need a list of the membership that don't have any expiration date so I can ask the client to tell me what to do with them.

**Comment by sagarjagdish** [comment]
Please see bellow attached file for the list of Member without exp. date.

[members with no expires date.xlsx](https://github.com/omnitekinc/AERA_MSS/files/796662/members.with.no.expires.date.xlsx)

**Comment by sagarjagdish** [comment]
@omnitekinc  We need client feedback on blank Join Date & Exp Date.
