### ISSUE TITLE
Fix ALL Query Times - Slow Load Times

### ISSUE THREAD

**Issue by karltonfrazier** [omnitekinc/AERA_MSS#33]
![screen shot 2017-03-03 at 2 15 48 pm](https://cloud.githubusercontent.com/assets/4383088/23571051/f1986f66-001b-11e7-9bb2-a879a876bab2.png)

**Comment by sagarjagdish** [comment]
I have checked today and all working fast. I think AERA server not capable to give us speed as there is many website hosted like 

- Prosis Pro Stage
- Prosis Pro Production
- Prosis Pro Demo
- aeraforum.com
- aeraedu.com
- AERA MMS

I also suggest below to change search function in individual search.

currently search is too much slow it's only because of the design. when we add any text in search we not know where it's match so all we need to match this text with all required column in database and then after result will be come. 

I have suggestion to make change in design like firs give option to user to selection on which column you want to preform your search like below and then add text to search box. In this case we need to target only on column in database to search instead to too many.

<img width="772" alt="search-by-option" src="https://cloud.githubusercontent.com/assets/7322922/23578580/392441e0-0100-11e7-9cea-e667d40b2223.png">

**Comment by omnitekinc** [comment]
Hi Sagar, ok, let's do that to speed things up.

**Comment by sagarjagdish** [comment]
We did change as suggested and now search faster, however server not capable enough to manage all website which I listed in my last comment.

**Comment by omnitekinc** [comment]
How come when I search for Stella these results show up, but "Stella" is not inside the ticket. 

Can we add a clear search button next to search?

![screen shot 2017-03-09 at 9 02 34 am](https://cloud.githubusercontent.com/assets/7178461/23761556/08b23994-04a8-11e7-9d4d-6b578ca81ced.png)

**Comment by sagarjagdish** [comment]
Hi Stella,

I have looked into this issue and notice one of the member name contains "stella". Please refer below image for reference. 

<img width="760" alt="membername-contains-stella" src="https://cloud.githubusercontent.com/assets/7322922/23887349/5133024a-08a7-11e7-8d00-a9d5f88b7641.png">
